version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "studi-superbowl"
    BUILD_ENV: "production"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
      runtime: version
    commands:
      - yarn install -g @angular/cli@16.0.6
  
  pre_build:
    on-failure: ABORT
  commands:
    - yarn install
  
  build :
    on-failure: ABORT
    steps:
      - if: ${{ env.S3_BUCKET == 'studi-superbowl' }}
        run: echo "S3 bucket is $S3_BUCKET"
    commands:
      - echo Build startd on `date`
      - cd dist/studi-superbowl
      - ls -la
      - aws s3 sync . s3://studi-superbowl --delete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist/studi-superbowl'
